Add function to insert previous sets values
treiher/valens pull request #61
Opened 2024-10-19 11:33 UTC by senier

This MR adds a shortcut to show and insert the values of the previous set (of the same session) into the current set. This avoids scrolling up (especially in super sets) to see the values that have been achieved in the previous set of the same exercise.

2024-10-19 16:03 UTC, treiher requested changes
I see the purpose of this extension and agree to add it. At some point I would like to get rid of all these shortcuts/values below the input fields. They take up vertical space and clutter the display. I think putting this information in a separate dialog as outlined in #59 would be a better solution. The freed vertical space could already be sufficient to see the values of previous sets, even for supersets. The main disadvantage would be that inserting the values would take two clicks instead of just one. What do you think?

2024-10-20 13:57 UTC, senier commented on CHANGELOG.md
> +- Shortcut for inserting previous sets values into current set
Changed

2024-10-20 13:59 UTC, senier commented on frontend/src/page/training_session.rs
> +                                prev_set.rpe.parsed.filter(|v| *v > 0.0),
Those are indeed unnecessary, I removed them. There was some issue in a previous version where empty fields resulted in zero which made me believe they are needed...

2024-10-20 14:04 UTC, senier commented
> I see the purpose of this extension and agree to add it. At some point I would like to get rid of all these shortcuts/values below the input fields. They take up vertical space and clutter the display. I think putting this information in a separate dialog as outlined in #59 would be a better solution. The freed vertical space could already be sufficient to see the values of previous sets, even for supersets. The main disadvantage would be that inserting the values would take two clicks instead of just one. What do you think?

I'm all in favor of uncluttering the guided workout screen (where a distraction free UI is most important, IMHO). It's not that bad for me right now, as I don't use TUT or RPE and only put the target reps in my routines (the rest is taken from the workout history) which saves some screen space. But I can see how this is much worse for someone using all those features.

I generally like the concept outlined in #59 - I'll add some comments there.

2024-10-20 15:59 UTC, senier commented on frontend/src/page/training_session.rs
> +                                prev_set.rpe.parsed.filter(|v| *v > 0.0),
I just realized that it doesn't work as expected without the filters. If the field of the previous set is empty and the `Msg::EnterPreviousSetValues` message is handled, then a `0` is entered into the current set for the respective fields. It's remove on the next update. Not sure why...

2024-10-20 17:27 UTC, treiher commented on frontend/src/page/training_session.rs
> +                                prev_set.rpe.parsed.filter(|v| *v > 0.0),
The filter is actually needed. The `parsed` field of `common::InputField` is also used to represent the validity of an input field:
 https://github.com/treiher/valens/blob/83ed35e4d6a7f7b102ab61862022e44e00b9ee12/frontend/src/common.rs#L61-L63

`Some(0)` is used to represent empty input fields and `None` for invalid input fields. In contrast for `prev_set_*` `Some(x)` is used to represent a value `x` that needs to be filled in and `None` for no value.

2024-10-20 19:06 UTC, senier commented on frontend/src/page/training_session.rs
> +                                prev_set.rpe.parsed.filter(|v| *v > 0.0),
That makes sense - thanks for the explanation. I reintroduced the filters (and rebased onto main).

2024-10-21 21:14 UTC, treiher approved these changes

2024-10-21 21:14 UTC, merged